# Form implementation generated from reading ui file 'd:\Corponariño TUA\app\ui\login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 617)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow.setMaximumSize(QtCore.QSize(500, 617))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(450, 200))
        self.label_7.setMaximumSize(QtCore.QSize(275, 120))
        self.label_7.setStyleSheet("alternate-background-color: rgb(119, 118, 123);\n"
"\n"
"    background-color: #16344D; /* Color de fondo */")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("d:\\Corponariño TUA\\app\\ui\\../../assets/icono.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.toolButton = QtWidgets.QToolButton(parent=self.frame)
        self.toolButton.setStyleSheet("border:none;\n"
"font:18px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Corponariño TUA\\app\\ui\\../../assets/iconos/user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(24, 24))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout.addWidget(self.toolButton)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 18px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.toolButton_2 = QtWidgets.QToolButton(parent=self.frame)
        self.toolButton_2.setStyleSheet("border:none;\n"
"font:18px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\Corponariño TUA\\app\\ui\\../../assets/iconos/padlock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout.addWidget(self.toolButton_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 18px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 45))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 2px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"    text-align: Center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D9844C; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "Usuario:"))
        self.toolButton_2.setText(_translate("MainWindow", "Contraseña:"))
        self.pushButton.setText(_translate("MainWindow", "Ingresar"))
