# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 615)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 600))
        Form.setMaximumSize(QtCore.QSize(500, 1448))
        Form.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.stackedWidgetPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(450, 200))
        self.label_7.setMaximumSize(QtCore.QSize(275, 120))
        self.label_7.setStyleSheet(
            "alternate-background-color: rgb(119, 118, 123);\n"
            "\n"
            "    background-color: #16344D; /* Color de fondo */"
        )
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("assets/icono.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(
            self.label_7, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop
        )
        spacerItem = QtWidgets.QSpacerItem(
            20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout.addItem(spacerItem)
        self.toolButton = QtWidgets.QToolButton(self.stackedWidgetPage1)
        self.toolButton.setStyleSheet("border:none;\n" "font:18px;")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("assets/iconos/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(24, 24))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout.addWidget(self.toolButton)
        self.lineEditUsuario = QtWidgets.QLineEdit(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEditUsuario.sizePolicy().hasHeightForWidth()
        )
        self.lineEditUsuario.setSizePolicy(sizePolicy)
        self.lineEditUsuario.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEditUsuario.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEditUsuario.setStyleSheet(
            "QLineEdit {\n"
            "\n"
            "    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
            "    border: none; /* Sin bordes generales */\n"
            "    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
            "    border-radius: 0px; /* Sin bordes redondeados */\n"
            "    padding: 5px; /* Espaciado interno */\n"
            "    font: 18px;\n"
            "QLineEdit {\n"
            "\n"
            "    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
            "    border: none; /* Sin bordes generales */\n"
            "    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
            "    border-radius: 0px; /* Sin bordes redondeados */\n"
            "    padding: 5px; /* Espaciado interno */\n"
            "    font: 10px;\n"
            "\n"
            "    margin-right: 8px; /* Margen a la derecha de 10px */\n"
            "}\n"
            "\n"
            "/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
            "QLineEdit:hover {\n"
            "    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
            "}\n"
            "\n"
            "/* Al hacer clic (foco), se mantiene igual que el hover */\n"
            "QLineEdit:focus {\n"
            "    border-bottom: 2px solid #16344D;\n"
            "    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
            "    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
            "}\n"
            "\n"
            "}\n"
            "\n"
            "/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
            "QLineEdit:hover {\n"
            "    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
            "}\n"
            "\n"
            "/* Al hacer clic (foco), se mantiene igual que el hover */\n"
            "QLineEdit:focus {\n"
            "    border-bottom: 2px solid #16344D;\n"
            "    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
            "    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
            "}\n"
            ""
        )
        self.lineEditUsuario.setText("")
        self.lineEditUsuario.setObjectName("lineEditUsuario")
        self.verticalLayout.addWidget(self.lineEditUsuario, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout.addItem(spacerItem1)
        self.toolButton_2 = QtWidgets.QToolButton(self.stackedWidgetPage1)
        self.toolButton_2.setStyleSheet("border:none;\n" "font:18px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("assets/iconos/padlock.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout.addWidget(self.toolButton_2)
        self.lineEditPassword = QtWidgets.QLineEdit(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEditPassword.sizePolicy().hasHeightForWidth()
        )
        self.lineEditPassword.setSizePolicy(sizePolicy)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEditPassword.setStyleSheet(
            "QLineEdit {\n"
            "\n"
            "    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
            "    border: none; /* Sin bordes generales */\n"
            "    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
            "    border-radius: 0px; /* Sin bordes redondeados */\n"
            "    padding: 5px; /* Espaciado interno */\n"
            "    font: 18px;\n"
            "QLineEdit {\n"
            "\n"
            "    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
            "    border: none; /* Sin bordes generales */\n"
            "    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
            "    border-radius: 0px; /* Sin bordes redondeados */\n"
            "    padding: 5px; /* Espaciado interno */\n"
            "    font: 10px;\n"
            "\n"
            "    margin-right: 8px; /* Margen a la derecha de 10px */\n"
            "}\n"
            "\n"
            "/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
            "QLineEdit:hover {\n"
            "    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
            "}\n"
            "\n"
            "/* Al hacer clic (foco), se mantiene igual que el hover */\n"
            "QLineEdit:focus {\n"
            "    border-bottom: 2px solid #16344D;\n"
            "    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
            "    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
            "}\n"
            "\n"
            "}\n"
            "\n"
            "/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
            "QLineEdit:hover {\n"
            "    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
            "}\n"
            "\n"
            "/* Al hacer clic (foco), se mantiene igual que el hover */\n"
            "QLineEdit:focus {\n"
            "    border-bottom: 2px solid #16344D;\n"
            "    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
            "    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
            "}\n"
            ""
        )
        self.lineEditPassword.setText("")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout.addWidget(self.lineEditPassword, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout.addItem(spacerItem2)
        self.BtnIngresar = QtWidgets.QPushButton(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnIngresar.sizePolicy().hasHeightForWidth())
        self.BtnIngresar.setSizePolicy(sizePolicy)
        self.BtnIngresar.setMinimumSize(QtCore.QSize(180, 45))
        self.BtnIngresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnIngresar.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #16344D; /* Color de fondo */\n"
            "    border-radius: 2px; /* Bordes redondeados */\n"
            "    color: white; /* Color del texto */\n"
            "    padding: 5px 10px; /* Espaciado interno */\n"
            "    border: none; /* Elimina el borde predeterminado */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "    text-align: Center; /* Alinea el texto a la izquierda */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #D9844C; /* Color de fondo al pasar el mouse */\n"
            "    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
            "    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
            "    transition: all 0.3s ease-in-out; /* Transición suave */\n"
            "}\n"
            "\n"
            "QPushButton::icon {\n"
            "    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
            "}\n"
            ""
        )
        self.BtnIngresar.setObjectName("BtnIngresar")
        self.verticalLayout.addWidget(self.BtnIngresar, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.verticalLayout_2.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.toolButton.setText(_translate("Form", "Usuario:"))
        self.toolButton_2.setText(_translate("Form", "Contraseña:"))
        self.BtnIngresar.setText(_translate("Form", "Ingresar"))
