# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Personal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Personal(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1584, 838)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(300, 600))
        Form.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.stackedWidget_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.stackedWidget_2Page1 = QtWidgets.QWidget()
        self.stackedWidget_2Page1.setObjectName("stackedWidget_2Page1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.stackedWidget_2Page1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.stackedWidget_2Page1)
        self.frame_6.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LineValorRecibo = QtWidgets.QLineEdit(self.frame_6)
        self.LineValorRecibo.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineValorRecibo.setObjectName("LineValorRecibo")
        self.gridLayout_4.addWidget(self.LineValorRecibo, 20, 5, 1, 1)
        self.LineFechaRadicado = QtWidgets.QLineEdit(self.frame_6)
        self.LineFechaRadicado.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineFechaRadicado.setObjectName("LineFechaRadicado")
        self.gridLayout_4.addWidget(self.LineFechaRadicado, 14, 3, 1, 1)
        self.LineCertificado = QtWidgets.QLineEdit(self.frame_6)
        self.LineCertificado.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineCertificado.setObjectName("LineCertificado")
        self.gridLayout_4.addWidget(self.LineCertificado, 18, 3, 1, 1)
        self.LineDireccion = QtWidgets.QLineEdit(self.frame_6)
        self.LineDireccion.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineDireccion.setObjectName("LineDireccion")
        self.gridLayout_4.addWidget(self.LineDireccion, 14, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 15, 3, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 3, 4, 1, 1)
        self.ComboTipoExpediente = QtWidgets.QComboBox(self.frame_6)
        self.ComboTipoExpediente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboTipoExpediente.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"    \n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboTipoExpediente.setObjectName("ComboTipoExpediente")
        self.gridLayout_4.addWidget(self.ComboTipoExpediente, 3, 5, 1, 1)
        self.ComboTipoUsuario = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboTipoUsuario.sizePolicy().hasHeightForWidth())
        self.ComboTipoUsuario.setSizePolicy(sizePolicy)
        self.ComboTipoUsuario.setMinimumSize(QtCore.QSize(200, 40))
        self.ComboTipoUsuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboTipoUsuario.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"    \n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboTipoUsuario.setObjectName("ComboTipoUsuario")
        self.ComboTipoUsuario.addItem("")
        self.ComboTipoUsuario.addItem("")
        self.gridLayout_4.addWidget(self.ComboTipoUsuario, 6, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 17, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.LineTarifaCobrar = QtWidgets.QLineEdit(self.frame_6)
        self.LineTarifaCobrar.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineTarifaCobrar.setObjectName("LineTarifaCobrar")
        self.gridLayout_4.addWidget(self.LineTarifaCobrar, 22, 5, 1, 1)
        self.LineNumeroLiquidacion = QtWidgets.QLineEdit(self.frame_6)
        self.LineNumeroLiquidacion.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineNumeroLiquidacion.setObjectName("LineNumeroLiquidacion")
        self.gridLayout_4.addWidget(self.LineNumeroLiquidacion, 20, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 7, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setStyleSheet("border:none;\n"
"font:20px;")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.LineCostoTotal = QtWidgets.QLineEdit(self.frame_6)
        self.LineCostoTotal.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineCostoTotal.setObjectName("LineCostoTotal")
        self.gridLayout_4.addWidget(self.LineCostoTotal, 18, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        self.label_14.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 15, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 7, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 9, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.LineNumeroExpediente = QtWidgets.QLineEdit(self.frame_6)
        self.LineNumeroExpediente.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font-size: 20px; /* Tamaño de fuente */\n"
"    margin-right: 8px; /* Margen derecho */\n"
"    text-align: center; /* Iniciar centrado */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando el cursor pasa por encima */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Resalta el borde inferior */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando está enfocado */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Fondo más claro */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Efecto de sombra */\n"
"}\n"
"")
        self.LineNumeroExpediente.setObjectName("LineNumeroExpediente")
        self.gridLayout_4.addWidget(self.LineNumeroExpediente, 1, 5, 1, 1)
        self.LineValorTabla = QtWidgets.QLineEdit(self.frame_6)
        self.LineValorTabla.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineValorTabla.setObjectName("LineValorTabla")
        self.gridLayout_4.addWidget(self.LineValorTabla, 22, 3, 1, 1)
        self.ComboRepresentanteLegal = QtWidgets.QComboBox(self.frame_6)
        self.ComboRepresentanteLegal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboRepresentanteLegal.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"    \n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboRepresentanteLegal.setObjectName("ComboRepresentanteLegal")
        self.gridLayout_4.addWidget(self.ComboRepresentanteLegal, 12, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        self.label_15.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 17, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.ComboTipoConcesion = QtWidgets.QComboBox(self.frame_6)
        self.ComboTipoConcesion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboTipoConcesion.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"    \n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboTipoConcesion.setObjectName("ComboTipoConcesion")
        self.gridLayout_4.addWidget(self.ComboTipoConcesion, 3, 3, 1, 1)
        self.LineCorreo = QtWidgets.QLineEdit(self.frame_6)
        self.LineCorreo.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineCorreo.setObjectName("LineCorreo")
        self.gridLayout_4.addWidget(self.LineCorreo, 16, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 13, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.ComboAreaRegistro = QtWidgets.QComboBox(self.frame_6)
        self.ComboAreaRegistro.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"    \n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboAreaRegistro.setObjectName("ComboAreaRegistro")
        self.gridLayout_4.addWidget(self.ComboAreaRegistro, 1, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 21, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 13, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 21, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 9, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 20, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.LineRazonSocial = QtWidgets.QLineEdit(self.frame_6)
        self.LineRazonSocial.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineRazonSocial.setObjectName("LineRazonSocial")
        self.gridLayout_4.addWidget(self.LineRazonSocial, 12, 3, 1, 1)
        self.LineTelefono = QtWidgets.QLineEdit(self.frame_6)
        self.LineTelefono.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineTelefono.setObjectName("LineTelefono")
        self.gridLayout_4.addWidget(self.LineTelefono, 16, 3, 1, 1)
        self.LineEstadoConcesion = QtWidgets.QLineEdit(self.frame_6)
        self.LineEstadoConcesion.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineEstadoConcesion.setObjectName("LineEstadoConcesion")
        self.gridLayout_4.addWidget(self.LineEstadoConcesion, 6, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 19, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 19, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 4, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.ComboTipoDocumento = QtWidgets.QComboBox(self.frame_6)
        self.ComboTipoDocumento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboTipoDocumento.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"    \n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboTipoDocumento.setObjectName("ComboTipoDocumento")
        self.gridLayout_4.addWidget(self.ComboTipoDocumento, 8, 3, 1, 1)
        self.LineNumeroDoc = QtWidgets.QLineEdit(self.frame_6)
        self.LineNumeroDoc.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineNumeroDoc.setObjectName("LineNumeroDoc")
        self.gridLayout_4.addWidget(self.LineNumeroDoc, 8, 5, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.stackedWidget_2Page1)
        self.frame_5.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(280, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.BtnCrear = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnCrear.sizePolicy().hasHeightForWidth())
        self.BtnCrear.setSizePolicy(sizePolicy)
        self.BtnCrear.setMinimumSize(QtCore.QSize(180, 45))
        self.BtnCrear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnCrear.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"    text-align: center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4C6D8C; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../assets/iconos/anadir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnCrear.setIcon(icon)
        self.BtnCrear.setIconSize(QtCore.QSize(24, 24))
        self.BtnCrear.setObjectName("BtnCrear")
        self.horizontalLayout_2.addWidget(self.BtnCrear, 0, QtCore.Qt.AlignRight)
        self.BtnActualizar = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnActualizar.sizePolicy().hasHeightForWidth())
        self.BtnActualizar.setSizePolicy(sizePolicy)
        self.BtnActualizar.setMinimumSize(QtCore.QSize(180, 45))
        self.BtnActualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnActualizar.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 2px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"    text-align: Center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525C5E; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../assets/iconos/actualizar-flecha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnActualizar.setIcon(icon1)
        self.BtnActualizar.setIconSize(QtCore.QSize(24, 24))
        self.BtnActualizar.setObjectName("BtnActualizar")
        self.horizontalLayout_2.addWidget(self.BtnActualizar, 0, QtCore.Qt.AlignRight)
        self.BtnBorrar = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnBorrar.sizePolicy().hasHeightForWidth())
        self.BtnBorrar.setSizePolicy(sizePolicy)
        self.BtnBorrar.setMinimumSize(QtCore.QSize(180, 45))
        self.BtnBorrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnBorrar.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"    text-align: center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D32F2F ; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../assets/iconos/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnBorrar.setIcon(icon2)
        self.BtnBorrar.setIconSize(QtCore.QSize(28, 28))
        self.BtnBorrar.setObjectName("BtnBorrar")
        self.horizontalLayout_2.addWidget(self.BtnBorrar, 0, QtCore.Qt.AlignRight)
        self.gridLayout_3.addWidget(self.frame_4, 2, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 50))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Linebuscador = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linebuscador.sizePolicy().hasHeightForWidth())
        self.Linebuscador.setSizePolicy(sizePolicy)
        self.Linebuscador.setMinimumSize(QtCore.QSize(500, 40))
        self.Linebuscador.setMaximumSize(QtCore.QSize(300, 25))
        self.Linebuscador.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 4px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 18px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.Linebuscador.setObjectName("Linebuscador")
        self.horizontalLayout_4.addWidget(self.Linebuscador)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_2.setMinimumSize(QtCore.QSize(45, 45))
        self.toolButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setStyleSheet("border:none;")
        self.toolButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../assets/iconos/people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon3)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_4.addWidget(self.toolButton_2)
        self.gridLayout_3.addWidget(self.frame_3, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.TablaPersonal = QtWidgets.QTableWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TablaPersonal.sizePolicy().hasHeightForWidth())
        self.TablaPersonal.setSizePolicy(sizePolicy)
        self.TablaPersonal.setMinimumSize(QtCore.QSize(600, 600))
        self.TablaPersonal.setStyleSheet("QTableWidget {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    border: 1px solid #CCCCCC; /* Borde suave */\n"
"    border-radius: 2px; /* Bordes redondeados */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    gridline-color: #DDDDDD; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Espaciado de las celdas */\n"
"    border-radius: 2px; /* Bordes redondeados en las celdas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #f0f0f0; /* Fondo claro al pasar el mouse */\n"
"    color: #16344D; /* Texto azul al pasar el mouse */\n"
"}\n"
"\n"
"/* Barra de desplazamiento vertical y horizontal */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    \n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    width: 7px; /* Ancho de la barra vertical */\n"
"    height: 7px; /* Alto de la barra horizontal */\n"
"}\n"
"\n"
"/* Manejador de la barra de desplazamiento (el \"handle\") */\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #16344D; /* Barra de desplazamiento en azul */\n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    min-height: 10px; /* Tamaño mínimo de la barra de desplazamiento vertical */\n"
"    min-width: 10px; /* Tamaño mínimo de la barra de desplazamiento horizontal */\n"
"}\n"
"\n"
"/* Efecto cuando el mouse pasa por encima del manejador */\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background-color: #1A4567; /* Fondo más oscuro al pasar el mouse */\n"
"}\n"
"\n"
"/* Líneas de los botones de desplazamiento (arriba/abajo o izquierda/derecha) */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none; /* Quitar los botones de desplazamiento */\n"
"}\n"
"\n"
"/* Flechas de los botones de desplazamiento */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none; /* Quitar las flechas */\n"
"}\n"
"")
        self.TablaPersonal.setObjectName("TablaPersonal")
        self.TablaPersonal.setColumnCount(20)
        self.TablaPersonal.setRowCount(24)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaPersonal.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaPersonal.setHorizontalHeaderItem(19, item)
        self.gridLayout_3.addWidget(self.TablaPersonal, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.stackedWidget_2.addWidget(self.stackedWidget_2Page1)
        self.verticalLayout_2.addWidget(self.stackedWidget_2)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Navbar"))
        self.label_7.setText(_translate("Form", "Teléfono:"))
        self.ComboTipoUsuario.setItemText(0, _translate("Form", "Nuevo elemento"))
        self.ComboTipoUsuario.setItemText(1, _translate("Form", "Nuevo elemento"))
        self.label_8.setText(_translate("Form", "Certificado de libertad y tradición:"))
        self.label_11.setText(_translate("Form", "Número de documento:"))
        self.label.setText(_translate("Form", "Tipo de concesión:"))
        self.label_14.setText(_translate("Form", "Correo electronico:"))
        self.label_4.setText(_translate("Form", "Tipo de documento:"))
        self.label_5.setText(_translate("Form", "Razon social:"))
        self.label_21.setText(_translate("Form", "Número de expediente:"))
        self.label_9.setText(_translate("Form", "Expediente:"))
        self.label_15.setText(_translate("Form", "Costo total del proyecto:"))
        self.label_13.setText(_translate("Form", "Dirección de correspondencia:"))
        self.label_18.setText(_translate("Form", "Valor tabla unica:"))
        self.label_6.setText(_translate("Form", "Fecha de radicado:"))
        self.label_19.setText(_translate("Form", "Tarifa a cobrar:"))
        self.label_12.setText(_translate("Form", "Representante legal:"))
        self.label_2.setText(_translate("Form", "Estado de la concesión:"))
        self.label_16.setText(_translate("Form", "Valor recibo de pago:"))
        self.label_17.setText(_translate("Form", "Número de liquidación:"))
        self.label_20.setText(_translate("Form", "Área de registro:"))
        self.label_10.setText(_translate("Form", "Tipo de usuario:"))
        self.BtnCrear.setText(_translate("Form", " Crear"))
        self.BtnActualizar.setText(_translate("Form", " Actualizar"))
        self.BtnBorrar.setText(_translate("Form", " Borrar"))
        item = self.TablaPersonal.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(1)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(2)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(3)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(4)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(5)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(6)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(7)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(8)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(9)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(10)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(11)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(12)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(13)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(14)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(15)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(16)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(17)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(18)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(19)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(20)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(21)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(22)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.verticalHeaderItem(23)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaPersonal.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Área d registro"))
        item = self.TablaPersonal.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Número de expediente"))
        item = self.TablaPersonal.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Tipo de concesion"))
        item = self.TablaPersonal.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Expediente"))
        item = self.TablaPersonal.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Estado concesion"))
        item = self.TablaPersonal.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Tipo usuario"))
        item = self.TablaPersonal.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Tipo documento"))
        item = self.TablaPersonal.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Numero documento"))
        item = self.TablaPersonal.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Razon social"))
        item = self.TablaPersonal.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Representante legal"))
        item = self.TablaPersonal.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Fecha radicado"))
        item = self.TablaPersonal.horizontalHeaderItem(11)
        item.setText(_translate("Form", "Dirección"))
        item = self.TablaPersonal.horizontalHeaderItem(12)
        item.setText(_translate("Form", "Teléfono"))
        item = self.TablaPersonal.horizontalHeaderItem(13)
        item.setText(_translate("Form", "Correo"))
        item = self.TablaPersonal.horizontalHeaderItem(14)
        item.setText(_translate("Form", "Certificado libertad"))
        item = self.TablaPersonal.horizontalHeaderItem(15)
        item.setText(_translate("Form", "Costo total"))
        item = self.TablaPersonal.horizontalHeaderItem(16)
        item.setText(_translate("Form", "Número liquidacion"))
        item = self.TablaPersonal.horizontalHeaderItem(17)
        item.setText(_translate("Form", "Valor recibo "))
        item = self.TablaPersonal.horizontalHeaderItem(18)
        item.setText(_translate("Form", "Valor tabla unica"))
        item = self.TablaPersonal.horizontalHeaderItem(19)
        item.setText(_translate("Form", "Tarifa a cobrar"))
