# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sidebar(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(306, 1448)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(300, 600))
        Form.setStyleSheet(
            "background-color: rgb(238, 238, 238);\n"
            "background-color: rgb(255, 255, 255);"
        )
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.stackedWidget.sizePolicy().hasHeightForWidth()
        )
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(250, 550))
        self.stackedWidget.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "border: 1px solid #d5d5d5;"
        )
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.stackedWidgetPage1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(250, 100))
        self.label.setMaximumSize(QtCore.QSize(250, 100))
        self.label.setStyleSheet(" background-color: #16344D; /* Color de fondo */")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../assets/icono.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_3.addItem(spacerItem)
        self.BtnExpediente = QtWidgets.QPushButton(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BtnExpediente.sizePolicy().hasHeightForWidth()
        )
        self.BtnExpediente.setSizePolicy(sizePolicy)
        self.BtnExpediente.setMinimumSize(QtCore.QSize(250, 45))
        self.BtnExpediente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnExpediente.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #16344D; /* Color de fondo */\n"
            "    border-radius: 2px; /* Bordes redondeados */\n"
            "    color: white; /* Color del texto */\n"
            "    padding: 5px 10px; /* Espaciado interno */\n"
            "    border: none; /* Elimina el borde predeterminado */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "    text-align: left; /* Alinea el texto a la izquierda */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #1A4567; /* Color de fondo al pasar el mouse */\n"
            "    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
            "    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
            "    transition: all 0.3s ease-in-out; /* Transición suave */\n"
            "}\n"
            "\n"
            "QPushButton::icon {\n"
            "    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
            "}\n"
            ""
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../../assets/iconos/expediente (1).png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnExpediente.setIcon(icon)
        self.BtnExpediente.setIconSize(QtCore.QSize(24, 24))
        self.BtnExpediente.setObjectName("BtnExpediente")
        self.verticalLayout_3.addWidget(self.BtnExpediente)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_3.addItem(spacerItem1)
        self.BtnResolucion = QtWidgets.QPushButton(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BtnResolucion.sizePolicy().hasHeightForWidth()
        )
        self.BtnResolucion.setSizePolicy(sizePolicy)
        self.BtnResolucion.setMinimumSize(QtCore.QSize(250, 50))
        self.BtnResolucion.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #16344D; /* Color de fondo */\n"
            "    border-radius: 2px; /* Bordes redondeados */\n"
            "    color: white; /* Color del texto */\n"
            "    padding: 5px 10px; /* Espaciado interno */\n"
            "    border: none; /* Elimina el borde predeterminado */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "    text-align: left; /* Alinea el texto a la izquierda */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #1A4567; /* Color de fondo al pasar el mouse */\n"
            "    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
            "    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
            "    transition: all 0.3s ease-in-out; /* Transición suave */\n"
            "}\n"
            "\n"
            "QPushButton::icon {\n"
            "    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
            "}\n"
            ""
        )
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("../../assets/iconos/legal.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnResolucion.setIcon(icon1)
        self.BtnResolucion.setIconSize(QtCore.QSize(32, 32))
        self.BtnResolucion.setObjectName("BtnResolucion")
        self.verticalLayout_3.addWidget(self.BtnResolucion)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_3.addItem(spacerItem2)
        self.BtnPUEAA = QtWidgets.QPushButton(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnPUEAA.sizePolicy().hasHeightForWidth())
        self.BtnPUEAA.setSizePolicy(sizePolicy)
        self.BtnPUEAA.setMinimumSize(QtCore.QSize(250, 45))
        self.BtnPUEAA.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #16344D; /* Color de fondo */\n"
            "    border-radius: 2px; /* Bordes redondeados */\n"
            "    color: white; /* Color del texto */\n"
            "    padding: 5px 10px; /* Espaciado interno */\n"
            "    border: none; /* Elimina el borde predeterminado */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "    text-align: left; /* Alinea el texto a la izquierda */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #1A4567; /* Color de fondo al pasar el mouse */\n"
            "    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
            "    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
            "    transition: all 0.3s ease-in-out; /* Transición suave */\n"
            "}\n"
            "\n"
            "QPushButton::icon {\n"
            "    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
            "}\n"
            ""
        )
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("../../assets/iconos/siembra.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnPUEAA.setIcon(icon2)
        self.BtnPUEAA.setIconSize(QtCore.QSize(24, 24))
        self.BtnPUEAA.setObjectName("BtnPUEAA")
        self.verticalLayout_3.addWidget(self.BtnPUEAA)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_3.addItem(spacerItem3)
        self.BtnMonitoreo = QtWidgets.QPushButton(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnMonitoreo.sizePolicy().hasHeightForWidth())
        self.BtnMonitoreo.setSizePolicy(sizePolicy)
        self.BtnMonitoreo.setMinimumSize(QtCore.QSize(250, 50))
        self.BtnMonitoreo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnMonitoreo.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #16344D; /* Color de fondo */\n"
            "    border-radius: 2px; /* Bordes redondeados */\n"
            "    color: white; /* Color del texto */\n"
            "    padding: 5px 10px; /* Espaciado interno */\n"
            "    border: none; /* Elimina el borde predeterminado */\n"
            "    font-size: 22px\n"
            "; /* Tamaño de fuente */\n"
            "    text-align: left; /* Alinea el texto a la izquierda */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #1A4567; /* Color de fondo al pasar el mouse */\n"
            "    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
            "    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
            "    transition: all 0.3s ease-in-out; /* Transición suave */\n"
            "}\n"
            "\n"
            "QPushButton::icon {\n"
            "    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
            "}\n"
            ""
        )
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("../../assets/iconos/stock-chart.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnMonitoreo.setIcon(icon3)
        self.BtnMonitoreo.setIconSize(QtCore.QSize(24, 24))
        self.BtnMonitoreo.setObjectName("BtnMonitoreo")
        self.verticalLayout_3.addWidget(self.BtnMonitoreo)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_3.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_3.addItem(spacerItem5)
        self.BtnRegistros = QtWidgets.QPushButton(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnRegistros.sizePolicy().hasHeightForWidth())
        self.BtnRegistros.setSizePolicy(sizePolicy)
        self.BtnRegistros.setMinimumSize(QtCore.QSize(250, 50))
        self.BtnRegistros.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnRegistros.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #16344D; /* Color de fondo */\n"
            "    border-radius: 2px; /* Bordes redondeados */\n"
            "    color: white; /* Color del texto */\n"
            "    padding: 5px 10px; /* Espaciado interno */\n"
            "    border: none; /* Elimina el borde predeterminado */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "    text-align: left; /* Alinea el texto a la izquierda */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #1A4567; /* Color de fondo al pasar el mouse */\n"
            "    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
            "    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
            "    transition: all 0.3s ease-in-out; /* Transición suave */\n"
            "}\n"
            "\n"
            "QPushButton::icon {\n"
            "    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
            "}\n"
            ""
        )
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("../../assets/iconos/folder.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnRegistros.setIcon(icon4)
        self.BtnRegistros.setIconSize(QtCore.QSize(24, 24))
        self.BtnRegistros.setObjectName("BtnRegistros")
        self.verticalLayout_3.addWidget(
            self.BtnRegistros, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop
        )
        spacerItem6 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_3.addItem(spacerItem6)
        self.BtnReportes = QtWidgets.QPushButton(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnReportes.sizePolicy().hasHeightForWidth())
        self.BtnReportes.setSizePolicy(sizePolicy)
        self.BtnReportes.setMinimumSize(QtCore.QSize(250, 50))
        self.BtnReportes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnReportes.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #16344D; /* Color de fondo */\n"
            "    border-radius: 2px; /* Bordes redondeados */\n"
            "    color: white; /* Color del texto */\n"
            "    padding: 5px 10px; /* Espaciado interno */\n"
            "    border: none; /* Elimina el borde predeterminado */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "    text-align: left; /* Alinea el texto a la izquierda */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #1A4567; /* Color de fondo al pasar el mouse */\n"
            "    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
            "    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
            "    transition: all 0.3s ease-in-out; /* Transición suave */\n"
            "}\n"
            "\n"
            "QPushButton::icon {\n"
            "    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
            "}\n"
            ""
        )
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap("../../assets/iconos/grafico-de-barras.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnReportes.setIcon(icon5)
        self.BtnReportes.setIconSize(QtCore.QSize(24, 24))
        self.BtnReportes.setObjectName("BtnReportes")
        self.verticalLayout_3.addWidget(
            self.BtnReportes, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop
        )
        spacerItem7 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_3.addItem(spacerItem7)
        self.BtnUsuarios = QtWidgets.QPushButton(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnUsuarios.sizePolicy().hasHeightForWidth())
        self.BtnUsuarios.setSizePolicy(sizePolicy)
        self.BtnUsuarios.setMinimumSize(QtCore.QSize(250, 45))
        self.BtnUsuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnUsuarios.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #16344D; /* Color de fondo */\n"
            "    border-radius: 2px; /* Bordes redondeados */\n"
            "    color: white; /* Color del texto */\n"
            "    padding: 5px 10px; /* Espaciado interno */\n"
            "    border: none; /* Elimina el borde predeterminado */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "    text-align: left; /* Alinea el texto a la izquierda */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #1A4567; /* Color de fondo al pasar el mouse */\n"
            "    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
            "    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
            "    transition: all 0.3s ease-in-out; /* Transición suave */\n"
            "}\n"
            "\n"
            "QPushButton::icon {\n"
            "    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
            "}\n"
            ""
        )
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap("../../assets/iconos/nuevo-usuario.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnUsuarios.setIcon(icon6)
        self.BtnUsuarios.setIconSize(QtCore.QSize(24, 24))
        self.BtnUsuarios.setObjectName("BtnUsuarios")
        self.verticalLayout_3.addWidget(self.BtnUsuarios, 0, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtWidgets.QSpacerItem(
            20, 700, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_3.addItem(spacerItem8)
        self.BtnSalir = QtWidgets.QPushButton(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnSalir.sizePolicy().hasHeightForWidth())
        self.BtnSalir.setSizePolicy(sizePolicy)
        self.BtnSalir.setMinimumSize(QtCore.QSize(180, 45))
        self.BtnSalir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnSalir.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #16344D; /* Color de fondo */\n"
            "    border-radius: 2px; /* Bordes redondeados */\n"
            "    color: white; /* Color del texto */\n"
            "    padding: 5px 10px; /* Espaciado interno */\n"
            "    border: none; /* Elimina el borde predeterminado */\n"
            "    font-size: 22px; /* Tamaño de fuente */\n"
            "    text-align: Center; /* Alinea el texto a la izquierda */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #D9844C; /* Color de fondo al pasar el mouse */\n"
            "    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
            "    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
            "    transition: all 0.3s ease-in-out; /* Transición suave */\n"
            "}\n"
            "\n"
            "QPushButton::icon {\n"
            "    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
            "}\n"
            ""
        )
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap("../../assets/iconos/cerrar-sesion.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnSalir.setIcon(icon7)
        self.BtnSalir.setIconSize(QtCore.QSize(24, 24))
        self.BtnSalir.setObjectName("BtnSalir")
        self.verticalLayout_3.addWidget(
            self.BtnSalir, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom
        )
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Navbar"))
        self.BtnExpediente.setText(_translate("Form", " Expedientes"))
        self.BtnResolucion.setText(_translate("Form", " Resolución"))
        self.BtnPUEAA.setText(_translate("Form", " PUEAA"))
        self.BtnMonitoreo.setText(_translate("Form", " Monitoreo"))
        self.BtnRegistros.setText(_translate("Form", " Registros"))
        self.BtnReportes.setText(_translate("Form", " Reportes"))
        self.BtnUsuarios.setText(_translate("Form", " Usuarios"))
        self.BtnSalir.setText(_translate("Form", " Salir"))
